export const UPDATE_TEMPERATURE = 'UPDATE_TEMPERATURE';
export const UPDATE_HUMIDITY = 'UPDATE_HUMIDITY';
export const UPDATE_FAN_SPEED = 'UPDATE_FAN_SPEED';
export const UPDATE_ZONE_TEMPERATURE = 'UPDATE_ZONE_TEMPERATURE';
export const ADD_ZONE = 'ADD_ZONE';
export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';